/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import AChardware.DBConn;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class CustomerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnPriceList = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbCat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("                                                                                                                   Copyright 2023 All Rights Reserved A & C Hardware");
        jLabel11.setMaximumSize(new java.awt.Dimension(1024, 50));
        jLabel11.setMinimumSize(new java.awt.Dimension(1024, 50));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(1024, 50));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1030, -1));

        tblStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Stocks Available", "Stocks Last Update"
            }
        ));
        jScrollPane1.setViewportView(tblStock);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 750, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gold Luxury Initial Circle Logo(3).jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(174, 0));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        jPanel1.setBackground(new java.awt.Color(241, 225, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("A&C Hardware");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 276, 50));

        jLabel4.setBackground(new java.awt.Color(242, 112, 164));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel4.setText("                                               Stock");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 48, 800, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jPanel2.setBackground(new java.awt.Color(241, 225, 77));
        jPanel2.setMinimumSize(new java.awt.Dimension(174, 618));
        jPanel2.setPreferredSize(new java.awt.Dimension(170, 618));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(241, 225, 77));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/giftbox(1).png"))); // NOI18N
        jButton2.setText("   Stock");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setPreferredSize(new java.awt.Dimension(174, 86));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 174, 86));

        btnPriceList.setBackground(new java.awt.Color(241, 225, 77));
        btnPriceList.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnPriceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-money(1).png"))); // NOI18N
        btnPriceList.setText(" Price List");
        btnPriceList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPriceList.setPreferredSize(new java.awt.Dimension(174, 86));
        btnPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceListActionPerformed(evt);
            }
        });
        jPanel2.add(btnPriceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 174, 86));

        jButton1.setBackground(new java.awt.Color(241, 225, 77));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home(1).png"))); // NOI18N
        jButton1.setText("   Home");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 174, 86));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 174, 620));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL" }));
        cmbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatActionPerformed(evt);
            }
        });
        jPanel3.add(cmbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 180, 27));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2552(1).jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 620));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 860, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChooseUser ch = new ChooseUser();
        ch.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceListActionPerformed
        // TODO add your handling code here:
        PriceList plist = new PriceList();
        plist.show();
        dispose();
    }//GEN-LAST:event_btnPriceListActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // add categories to combo box
        
        DBConn dbConn = new DBConn();
        Connection conn = dbConn.conn();
                
        try {
            Statement stm = (Statement) conn.createStatement();
            
            String sql = "select * from category;";
            ResultSet rs = stm.executeQuery(sql);
                
            while (rs.next()){
                cmbCat.addItem(rs.getString("CAT_NAME"));
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // add items to table
        try {
            Statement stm2 = (Statement) conn.createStatement();
            
            String sql = "SELECT i.ITEM_ID, i.ITEM_NAME, s.AVAILABLE_QTY, s.DATE\n "
                            + " FROM ITEM_ i\n "
                            + " LEFT JOIN SUPPLY s ON i.ITEM_ID = s.ITEM_ID;";
            
            ResultSet rs = stm2.executeQuery(sql);
                
            while (rs.next()){
                String itmID = String.valueOf(rs.getString("ITEM_ID"));
                String itmName = String.valueOf(rs.getString("ITEM_NAME"));
                String avbQty = String.valueOf(rs.getString("AVAILABLE_QTY"));
                String date = String.valueOf(rs.getDate("DATE"));
                
                //string array for store data into table
                String tbData[] = {itmID,itmName,avbQty,date};
                DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();
                
                //add string array data into tblStock
                tblModel.addRow(tbData);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void cmbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatActionPerformed
        // TODO add your handling code here:
        String selectedvalue = cmbCat.getSelectedItem().toString();
        
        DBConn dbConn = new DBConn();
        Connection conn = dbConn.conn();
        
        if (selectedvalue.equals("ALL")){
            
            //remove items from table
            try{
                int j = tblStock.getRowCount();
                DefaultTableModel dtm = (DefaultTableModel) tblStock.getModel();

                for (int k=0; k<j; k++){
                    dtm.removeRow(0);
                }
            }
            catch(ArrayIndexOutOfBoundsException e){
                System.out.println(e.getMessage()); 
            }
            
            // add items to table
            try {
                Statement stm2 = (Statement) conn.createStatement();

                String sql = "SELECT i.ITEM_ID, i.ITEM_NAME, s.AVAILABLE_QTY, s.DATE\n "
                                + " FROM ITEM_ i\n "
                                + " LEFT JOIN SUPPLY s ON i.ITEM_ID = s.ITEM_ID;";

                ResultSet rs = stm2.executeQuery(sql);

                while (rs.next()){
                    String itmID = String.valueOf(rs.getString("ITEM_ID"));
                    String itmName = String.valueOf(rs.getString("ITEM_NAME"));
                    String avbQty = String.valueOf(rs.getString("AVAILABLE_QTY"));
                    String date = String.valueOf(rs.getDate("DATE"));

                    //string array for store data into table
                    String tbData[] = {itmID,itmName,avbQty,date};
                    DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();

                    //add string array data into tblStock
                    tblModel.addRow(tbData);
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else{
            //remove items from table
            try{
                int j = tblStock.getRowCount();
                DefaultTableModel dtm = (DefaultTableModel) tblStock.getModel();

                for (int k=0; k<j; k++){
                    dtm.removeRow(0);
                }
            }
            catch(ArrayIndexOutOfBoundsException e){
                System.out.println(e.getMessage()); 
            }

            // add items to table
            try {
                Statement stm3 = (Statement) conn.createStatement();

                String sql = "SELECT i.ITEM_ID, i.ITEM_NAME, s.AVAILABLE_QTY, s.DATE\n "
                                + " FROM ITEM_ i\n "
                                + " LEFT JOIN SUPPLY s ON i.ITEM_ID = s.ITEM_ID"
                                + " LEFT JOIN CATEGORY c ON i.CAT_ID = c.CAT_ID"
                                + " WHERE c.CAT_NAME = '"+selectedvalue+"';";

                ResultSet rs = stm3.executeQuery(sql);

                while (rs.next()){
                    String itmID = String.valueOf(rs.getString("ITEM_ID"));
                    String itmName = String.valueOf(rs.getString("ITEM_NAME"));
                    String avbQty = String.valueOf(rs.getString("AVAILABLE_QTY"));
                    String date = String.valueOf(rs.getDate("DATE"));

                    //string array for store data into table
                    String tbData[] = {itmID,itmName,avbQty,date};
                    DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();

                    //add string array data into tblStock
                    tblModel.addRow(tbData);
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
    }//GEN-LAST:event_cmbCatActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ChooseUser ch = new ChooseUser();
        ch.show();
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPriceList;
    private javax.swing.JComboBox<String> cmbCat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables
}
